#!/usr/bin/perl
# vi: set ts=4 sw=4 :

use warnings;
use strict;

print <<EOF;
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg width="100%" height="100%" version="1.1"
	xmlns="http://www.w3.org/2000/svg"
	xmlns:xlink="http://www.w3.org/1999/xlink">
EOF

my $size = 280;

my $seq = 0;
for my $row (0..9) {
	for my $col (0..13) {
		++$seq;
		my $file = sprintf "galt-%03d.svg", $seq;

		my $x = $size * $col;
		my $y = $size * $row;
		print <<EOF;
<image x="$x" y="$y" width="$size" height="$size" xlink:href="$file"/>
EOF
	}
}

print <<EOF;
</svg>
EOF
